"""create instagram posts table

Revision ID: 002
Revises: 001
Create Date: 2025-10-18 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('display_url', sa.String(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('first_comment', sa.Text(), nullable=True),
    sa.Column('latest_comments', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('dimensions_height', sa.Integer(), nullable=True),
    sa.Column('dimensions_width', sa.Integer(), nullable=True),
    sa.Column('owner_full_name', sa.String(), nullable=False),
    sa.Column('owner_username', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('tagged_users', sa.JSON(), nullable=True),
    sa.Column('is_comments_disabled', sa.Boolean(), nullable=True),
    sa.Column('input_url', sa.String(), nullable=False),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('child_posts', sa.JSON(), nullable=True),
    sa.Column('extracted_keywords', sa.JSON(), nullable=True),
    sa.Column('detected_objects', sa.JSON(), nullable=True),
    sa.Column('dominant_colors', sa.JSON(), nullable=True),
    sa.Column('style_attributes', sa.JSON(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('scraped_date', sa.DateTime(), nullable=True),
    sa.Column('primary_image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_posts_id'), 'instagram_posts', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_posts_owner_id'), 'instagram_posts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_instagram_posts_owner_username'), 'instagram_posts', ['owner_username'], unique=False)
    op.create_index(op.f('ix_instagram_posts_short_code'), 'instagram_posts', ['short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_posts_short_code'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_owner_username'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_owner_id'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_id'), table_name='instagram_posts')
    op.drop_table('instagram_posts')
    # ### end Alembic commands ###